version: '3.9'

services: 
  freedev-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    tty: true
    command: tail -f /dev/null
    extra_hosts:
      - host.docker.internal:host-gateway